swagger: '2.0'
info:
  title: Iris Classification API
  version: "0.1"
  description: An API that can classify Iris flowers

paths:
  /health:
    get:
      summary: Checks the health of the service
      description: Returns the health status of the service
      operationId: iris_classification_api.health
      responses:
        '200':
          description: Service is healthy
        '500':
          description: Service is unhealthy

  /predict:
    post:
      summary: Entrypoint to our prediction function
      operationId: iris_classification_api.predict
      consumes:
      - multipart/form-data
      produces:
      - application/json
      parameters:
        - in: formData
          name: sepal_length
          required: true
          description: Sepal length (cm)
          type: number
        - in: formData
          name: sepal_width
          required: true
          description: Sepal width (cm)
          type: number
        - in: formData
          name: petal_length
          required: true
          description: Petal length (cm)
          type: number
        - in: formData
          name: petal_width
          required: true
          description: Petal width (cm)
          type: number
      responses:
        '200':
          description: Classification performed successfully
        '500':
          description: Unable to perform the classification
